#!/usr/bin/env ruby

# encoding: utf-8

#  Copyright (c) 2018, Puzzle ITC GmbH. This file is part of
#  2Openproject and licensed under the Affero General Public License version 3 or later.
#  See the COPYING file at the top-level directory or at
#  https://github.com/puzzle/2Openproject.

require 'date'
require 'json'
require 'uri'
require 'net/http'
require 'rest-client'
require './lib/openproject_workpackage.rb'
require './lib/exporter.rb'
require './lib/option_handler.rb'
require './lib/importers/importer.rb'
require './lib/importers/bugzilla_importer.rb'
require './lib/importers/otrs_importer.rb'
require 'active_support/inflector'
require 'sequel'
require 'mysql2'
require 'yaml'

include OptionHandler

  def self.execute
    raise 'Ruby Version has to be equal or greater than 1.9.3' if Gem::Version.new(RUBY_VERSION) < Gem::Version.new('1.9.3')
    options = OptionHandler.parse

    openproject_workpackages = Importer.export_issues(options)
    e = Exporter.new(openproject_workpackages, options[:url], options[:project_id], options[:apikey])
    e.export
# e.update
#    puts "#{openproject_workpackages.count} issues exported to openproject successfully!"
  end

execute
